version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-component-paste-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY} 